name: tf-metal
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - tensorflow-deps=2.10
  - pip:
    - tensorflow-macos==2.10.*
    - tensorflow-metal==0.6.*  # optional, but recommended
    - pandas==1.5.*
    - seaborn==0.12.*
    - jupyterlab==3.4.*
    - -e .
